{"uuid":"3b6d578f-a5f2-4799-8d04-3344691f10f4","historyId":"9e1bc808f3b7969ea05efdb08626e7cc","fullName":"testCases.LoginPopUpTest.loginPopUpErrorMessageValidationInvalidUsername","labels":[{"name":"package","value":"testCases.LoginPopUpTest"},{"name":"testClass","value":"testCases.LoginPopUpTest"},{"name":"testMethod","value":"loginPopUpErrorMessageValidationInvalidUsername"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"testCases"},{"name":"subSuite","value":"testCases.LoginPopUpTest"},{"name":"host","value":"DESKTOP-PO3T4V3"},{"name":"thread","value":"17352@DESKTOP-PO3T4V3.TestNG-tests-1(19)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"minor"}],"links":[],"name":"Validate on Log_in Pop Up Error message with invalid password","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [Username or Password is incorrect. Please try again.] but found [Younger]","trace":"java.lang.AssertionError: expected [Username or Password is incorrect. Please try again.] but found [Younger]\r\n\tat org.testng.Assert.fail(Assert.java:110)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1413)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:149)\r\n\tat org.testng.Assert.assertEquals(Assert.java:131)\r\n\tat org.testng.Assert.assertEquals(Assert.java:655)\r\n\tat org.testng.Assert.assertEquals(Assert.java:665)\r\n\tat testCases.LoginPopUpTest.loginPopUpErrorMessageValidationInvalidUsername(LoginPopUpTest.java:259)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:806)\r\n\tat org.testng.TestRunner.run(TestRunner.java:601)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:433)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)\r\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\n"},"stage":"finished","description":"Validate on Log_in Pop Up error message with invalid password","steps":[],"attachments":[{"name":"loginPopUpErrorMessageValidationInvalidUsername_","source":"33ed88fd-8852-4d3e-8b28-2af35a58eacd-attachment"}],"parameters":[],"start":1658386641255,"stop":1658386644457}