<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-52C1ANV" failures="2" tests="4" name="craftBetAutomation" time="23.983" errors="0" timestamp="2022-07-05T20:23:55 AMT">
  <testcase classname="testCases.LoginTest" name="TestSuccess" time="0.364"/>
  <testcase classname="testCases.LoginTest" name="testFail" time="0.699">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.LoginTest.testFail(LoginTest.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase classname="testCases.LoginTest" name="testSkipp" time="0.004">
    <skipped/>
  </testcase> <!-- testSkipp -->
  <testcase classname="testCases.LoginTest" name="loginPopUpGUI_Test" time="0.586">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Log In     ] but found [Log In]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Log In     ] but found [Log In]
at testCases.LoginTest.loginPopUpGUI_Test(LoginTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginPopUpGUI_Test -->
</testsuite> <!-- craftBetAutomation -->
